name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main
    - name: Get net version
      uses: thenativeweb/get-next-version@main
      id: get_next_version
    - name: Create New Release
      if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
      run: |
        NEXT_VERSION=${{ steps.get_next_version.outputs.version }}
        git tag $NEXT_VERSION
        git push origin $NEXT_VERSION

    - name: Create GitHub Release
      if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
      uses: softprops/action-gh-release@v1
      with:
        files: '**/*'
        tag_name: ${{ steps.get_next_version.outputs.version }}
        release_name: Release ${{ steps.get_next_version.outputs.version }}
        body: Release notes for version ${{ steps.get_next_version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
