name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get net version
      uses: thenativeweb/get-next-version@main
      id: get_next_version
    - name: Create New Release
      if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
      run: |
        NEXT_VERSION=${{ steps.get_next_version.outputs.version }}
        git tag $NEXT_VERSION
        git push origin $NEXT_VERSION
